In [1]:
import sklearn.externals
import joblib

In [2]:
mj = joblib.load('model_joblib')

In [3]:
mj.coef_

array([135.78767123])

In [4]:
mj.intercept_

np.float64(180616.43835616432)

In [5]:
mj.predict([[4000]])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([723767.12328767])

In [6]:
mj.predict([[2000]])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([452191.78082192])